name = "ComoniconCast"
uuid = "2bbb4240-95bb-46d7-bd8b-1a3bc1aee33c"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ComoniconOptions = "a25bc8ac-9d24-42b2-8edd-3d267ec19fc5"
ComoniconTypes = "d0eb39ce-029e-40d1-add6-e32b3165f6a3"
ExproniconLite = "55351af7-c7e9-48d6-89ff-24e801d99491"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ComoniconOptions = "0.1"
ComoniconTypes = "0.1, 0.2"
ExproniconLite = "0.6"
julia = "1.6.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
